name: Cypress petlove e2e Tests
# on: [push]
# Trigger tanto manual (dispatch) quanto push
on:
  # push: []
  workflow_dispatch:
    inputs:
      #spec customizado para rodar diferentes suites de testes
      spec:
        default: cypress/e2e/*
jobs:
  chrome-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:22.16.0
      options: --user 1001 # parâmetro para subir a máquina como admin para não ter problemas com restrições
    strategy:
      # Se o teste falhar em uma instância, todas as outras instâncias falharam
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install # Instalando todas as dependências do projeto
          wait-on: 'https://petlov.vercel.app/'
          browser: chrome
          group: Chrome # Agrupar os dados e facilitar análise de dados
          record: true
          parallel: true
          
          # Executa todos os testes em spec podendo ser, todos regressão, mais ríticos smoke.
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Não precisa configurar, já vem por padrão

  firefox-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:22.16.0
      options: --user 1001 # parâmetro para subir a máquina como admin para não ter problemas com restrições
    strategy:
      # Se o teste falhar em uma instância, todas as outras instâncias falharam
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install # Instalando todas as dependências do projeto
          wait-on: 'https://petlov.vercel.app/'
          browser: firefox
          group: Firefox # Agrupar os dados e facilitar análise de dados
          record: true
          parallel: true
          
          # Executa todos os testes em spec podendo ser, todos regressão, mais ríticos smoke.
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Não precisa configurar, já vem por padrão